/*
 * This Scala source file was generated by the Gradle 'init' task.
 */

package com.github.mituba

import java.io.File

import scala.io.Source


object Main {
  def createClassInformation(filename: String): List[ClassInformation] ={
    val fileSource = Source.fromFile(filename)
    fileSource.getLines().map(_.split(",", 4))
      .filter(_.length >= 4)
      .map(n => new ClassInformation(filename = n(0), place = n(1), birthmark = "2-gram", data = n(3))).toList
  }

  def printCompareResults(algorithm: String, compareResults: List[CompareResult]): Unit ={
    compareResults.foreach(n =>
      printf("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n", algorithm, n.class1.filename, n.class1.place, n.class1.birthmark, n.class1.data,
      n.class2.filename, n.class2.place, n.class2.birthmark, n.class2.data, n.sim))
  }

  def printSearchResults(algorithm: String, compareResults: List[SeachResult]): Unit ={
    compareResults.foreach(n =>
      printf("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n", algorithm, n.class1.filename, n.class1.place, n.class1.birthmark, n.class1.data,
        n.class2.filename, n.class2.place, n.class2.birthmark, n.class2.data, n.sim))
  }

  def main(args: Array[String]): Unit = {

    val list: List[String] = List("jw", "edit", "ngram")
    val classInformations: List[ClassInformation] = createClassInformation(args(0))
    val searchResults: List[SeachResults] = list.flatMap(n =>
      classInformations.map(m => new SeachResults(n, new Searcher().search(m, n)))
    )

    searchResults.foreach(n => printSearchResults(n.algorithm, n.seachResults))



//    val compareResultsList: List[CompareResults] = searchResults.map(n => n.runCompare())
//    compareResultsList.foreach(n => printCompareResults(n.algorithm, n.compareResults))
  }
}
